### ISSUE TITLE
[flaky] DataVolume with block mode should [test_id:3944]succeed warm import from ImageIO to block volume expand_more

### ISSUE THREAD

**Issue by brybacki** [kubevirt/containerized-data-importer#2145]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
according to 
https://testgrid.k8s.io/kubevirt-containerized-data-importer-presubmits#pull-containerized-data-importer-e2e-k8s-1.21-ceph&width=20
`test Tests Suite: [vendor:cnv-qe@redhat.com][level:component]DataVolume tests Verify DataVolume with block mode should [test_id:3944]succeed warm import from ImageIO to block volume` now almost always fails

PVC has following error:
```
"Unable to connect to imageio data source: HTTP response code is \"404\". HTTP response message is \"404 Not Found\". Error sending transfer image request kubevirt.io/containerized-data-importer/pkg/importer.getTransfer \tpkg/importer/imageio-datasource.go:844 kubevirt.io/containerized-data-importer/pkg/importer.createImageioReader \tpkg/importer/imageio-datasource.go:519 kubevirt.io/containerized-data-importer/pkg/importer.NewImageioDataSource \tpkg/importer/imageio-datasource.go:71 main.newDataSource \tcmd/cdi-importer/importer.go:213 main.main \tcmd/cdi-importer/importer.go:134 runtime.main \tGOROOT/src/runtime/proc.go:255 runtime.goexit \tGOROOT/src/runtime/asm_amd64.s:1581",
```
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/2142/pull-containerized-data-importer-e2e-k8s-1.21-ceph/1490986369785270272/artifacts/1_pvcs.log

No there is an error in the fake imageio container
```
2022-02-08 17:29:14,946 DEBUG   (Thread-9) [backends.file] Open backend path=/images/cirros-snapshot2.qcow2 mode=rb sparse=False)
2022-02-08 17:29:14,946 DEBUG   (Thread-9) [backends.file] Trying block size 1
2022-02-08 17:29:14,946 DEBUG   (Thread-9) [backends.file] Trying block size 512
2022-02-08 17:29:14,946 DEBUG   (Thread-9) [backends.file] Detected block size 512
2022-02-08 17:29:14,946 INFO    (Thread-9) [images] [10.244.196.156] READ size=655360 offset=0 ticket=cirros-snapshot2.qcow2
2022-02-08 17:29:14,956 ERROR   (Thread-9) [http] Request aborted after starting response
Traceback (most recent call last):
  File "/ovirt-imageio/daemon/ovirt_imageio/ops.py", line 91, in _run
    self._send_chunk(buf)
  File "/ovirt-imageio/daemon/ovirt_imageio/ops.py", line 111, in _send_chunk
    self._dst.write(view)
  File "/ovirt-imageio/daemon/ovirt_imageio/http.py", line 452, in write
    self._con.wfile.write(data)
  File "/usr/lib64/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
  File "/usr/lib64/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib64/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer
```
So during the warm migration it trying to generate some snapshot files, and it is failing on the second one. I don't know why

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by brybacki** [comment]
https://github.com/kubevirt/containerized-data-importer/pull/2148
