### ISSUE TITLE
`DataVolume` validation webhook fails when presented with a `DataVolume` that provides a `StorageSpec` but without `DataVolumeSource`.

### ISSUE THREAD

**Issue by lyarwood** [kubevirt/containerized-data-importer#2502]
**What happened**:

The below `DataVolume` validation webhook code fails when presented with the following valid `DataVolume`:

```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: cirros-dv
spec:
  storage: {}
  sourceRef:
    kind: DataSource
    name: cirros
    namespace: default
```

https://github.com/kubevirt/containerized-data-importer/blob/43ee44af907b9ff0d28ca42007f7f3d642fc2bd6/pkg/apiserver/webhooks/datavolume-validate.go#L449

```
│ 2022/12/07 14:05:33 http: panic serving 192.168.66.101:59245: runtime error: invalid memory address or nil pointer dereference                                                                                  │
│ goroutine 5250 [running]:                                                                                                                                                                                       │
│ net/http.(*conn).serve.func1()                                                                                                                                                                                  │
│     GOROOT/src/net/http/server.go:1825 +0xbf                                                                                                                                                                    │
│ panic({0x17c5560, 0x2b55130})                                                                                                                                                                                   │
│     GOROOT/src/runtime/panic.go:844 +0x258                                                                                                                                                                      │
│ kubevirt.io/containerized-data-importer/pkg/apiserver/webhooks.validateStorageSize(0xc000d61d38, 0xc000728f90)                                                                                                  │
│     pkg/apiserver/webhooks/datavolume-validate.go:449 +0x2e5                                                                                                                                                    │
│ kubevirt.io/containerized-data-importer/pkg/apiserver/webhooks.(*dataVolumeValidatingWebhook).validateDataVolumeSpec(0x1cac4e0?, 0xc00002eea0, 0xc000728f90, 0xc000d61d38, 0x0?)                                │
│     pkg/apiserver/webhooks/datavolume-validate.go:97 +0x109                                                                                                                                                     │
│ kubevirt.io/containerized-data-importer/pkg/apiserver/webhooks.(*dataVolumeValidatingWebhook).Admit(0xc0000bd0c0, {{{0xc0006b8550, 0xf}, {0xc00078b098, 0x13}}, 0xc00002eea0, 0x0})                             │
│     pkg/apiserver/webhooks/datavolume-validate.go:544 +0xc6f                                                                                                                                                    │
│ kubevirt.io/containerized-data-importer/pkg/apiserver/webhooks.(*admissionHandler).ServeHTTP(0xc0007a37a0, {0x1cc3dd8, 0xc00022ee00}, 0xc0009f2900?)                                                            │
│     pkg/apiserver/webhooks/handler.go:124 +0x44a                                                                                                                                                                │
│ net/http.(*ServeMux).ServeHTTP(0x3b?, {0x1cc3dd8, 0xc00022ee00}, 0xc0009f2900)                                                                                                                                  │
│     GOROOT/src/net/http/server.go:2462 +0x149                                                                                                                                                                   │
│ kubevirt.io/containerized-data-importer/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc000a1279a?, {0x1cc3dd8?, 0xc00022ee00?}, 0x40ee85?)                                                     │
│     vendor/github.com/emicklei/go-restful/container.go:311 +0x1f5                                                                                                                                               │
│ net/http.serverHandler.ServeHTTP({0x1cb6280?}, {0x1cc3dd8, 0xc00022ee00}, 0xc0009f2900)                                                                                                                         │
│     GOROOT/src/net/http/server.go:2916 +0x43b                                                                                                                                                                   │
│ net/http.(*conn).serve(0xc0003ea320, {0x1cc4810, 0xc000763380})                                                                                                                                                 │
│     GOROOT/src/net/http/server.go:1966 +0x5d7                                                                                                                                                                   │
│ created by net/http.(*Server).Serve                                                                                                                                                                             │
│     GOROOT/src/net/http/server.go:3071 +0x4db          
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

```
wget https://github.com/cirros-dev/cirros/releases/download/0.6.1/cirros-0.6.1-x86_64-disk.img
[..]
./cluster-up/virtctl.sh image-upload pvc cirros --size=1Gi --image-path=./cirros-0.6.1-x86_64-disk.img
[..]
./cluster-up/kubectl.sh apply -f - <<EOF
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataSource
metadata:
  name: cirros
spec:
  source:
    pvc:
      name: cirros
      namespace: default
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: cirros-dv
spec:
  storage: {}
  sourceRef:
    kind: DataSource
    name: cirros
    namespace: default
EOF
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "datavolume-validate.cdi.kubevirt.io": failed to call webhook: Post "https://cdi-api.cdi.svc:443/datavolume-validate?timeout=30s": EOF
```

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): N/A
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by alromeros** [comment]
Hi @lyarwood, thanks for opening the issue!

You are right, that datavolume should be valid. Do you want any reviews on the linked PR?

**Comment by lyarwood** [comment]
> Hi @lyarwood, thanks for opening the issue!
> 
> You are right, that datavolume should be valid. Do you need any reviews on the linked PR?

I'll clean the PR up tomorrow and then yes I would appreciate some reviews once it's ready.

**Comment by lyarwood** [comment]
> Hi @lyarwood, thanks for opening the issue!
> 
> You are right, that datavolume should be valid. Do you need any reviews on the linked PR?

@alromeros, I'm trying to get tests written for this but the validations are very poorly documented. If the previously suggested `DataVolume` definition is valid do I also need to change the following `validateExternalPopulation` validation?

https://github.com/kubevirt/containerized-data-importer/blob/06c1dca5e714b7a7c95c5fabb095635a8312a3fb/pkg/apiserver/webhooks/datavolume-validate.go#L517-L523

**Comment by alromeros** [comment]
Hey @lyarwood, I don't think you need to change anything in `validateExternalPopulation` since an externally populated DataVolume shouldn't have either Source or SourceRef.

All the changes should be in `validateStorageSize`, as only clones allow empty storage size.

Something like:
```go
isClone := spec.SourceRef != nil || (spec.Source != nil && spec.Source.PVC != nil)
...
} else if spec.Storage == nil || !isClone {
...
``` 

Would work.

**Comment by lyarwood** [comment]
Yeah apologies I was confused by output from other tests, I've updated the PR now.
