### ISSUE TITLE
cdi-deployment crashloops on k8s 1.13

### ISSUE THREAD

**Issue by karmab** [kubevirt/containerized-data-importer#696]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
cdi-deployment crashloops on k8s 1.13. other cdi pods are up

**What you expected to happen**:
dont crashloop

**How to reproduce it (as minimally and precisely as possible)**:
deploy latest cdi release (using operator manifest) on top of k8s 1.13 

**Anything else we need to know?**:

logs from the pod

```
I0308 12:54:28.099910       1 controller.go:73] Note: increase the -v level in the controller deployment for more detailed logging, eg. -v=2 or -v=3
W0308 12:54:28.101064       1 client_config.go:548] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0308 12:54:28.132255       1 leaderelection.go:52] Attempting to acquire leader lease
I0308 12:54:28.133135       1 leaderelection.go:205] attempting to acquire leader lease  cdi/cdi-controller-leader-election-helper...
I0308 12:54:45.829693       1 leaderelection.go:214] successfully acquired lease cdi/cdi-controller-leader-election-helper
I0308 12:54:45.831248       1 leaderelection.go:105] Successfully acquired leadership lease
I0308 12:54:45.831266       1 controller.go:88] Starting CDI controller components
I0308 12:54:45.833192       1 controller.go:167] created cdi controllers
I0308 12:54:45.836496       1 controller.go:178] started informers
I0308 12:54:45.865818       1 keystore.go:79] Retrieved CA key/cert server.upload.cdi.kubevirt.io from kubernetes
I0308 12:54:45.872163       1 keystore.go:79] Retrieved CA key/cert client.upload-server.cdi.kubevirt.io from kubernetes
I0308 12:54:45.882213       1 keystore.go:161] Retrieved client key/cert uploadproxy.client.upload-server.cdi.kebevirt.io from kubernetes
E0308 12:54:45.887121       1 config-controller.go:319] Error updating CDI Config: cdiconfigs.cdi.kubevirt.io "config" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
F0308 12:54:45.888942       1 controller.go:211] Error running config controller: %+v Error creating CDI config: Error updating CDI Config: cdiconfigs.cdi.kubevirt.io "config" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
goroutine 66 [running]:
kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog.stacks(0xc000492100, 0xc00088a360, 0x10a, 0x118)
	/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog/glog.go:769 +0xd4
kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog.(*loggingT).output(0x1ed8a20, 0xc000000003, 0xc000120000, 0x1e3e0c9, 0xd, 0xd3, 0x0)
	/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog/glog.go:720 +0x329
kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog.(*loggingT).println(0x1ed8a20, 0x726f662200000003, 0xc000507f98, 0x2, 0x2)
	/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog/glog.go:633 +0xe7
kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog.Fatalln(0xc000507f98, 0x2, 0x2)
	/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/golang/glog/glog.go:1141 +0x53
main.start.func8(0xc0001de1e0, 0xc00008e120, 0xc0005feee0)
	/go/src/kubevirt.io/containerized-data-importer/cmd/cdi-controller/controller.go:211 +0xbb
created by main.start
	/go/src/kubevirt.io/containerized-data-importer/cmd/cdi-controller/controller.go:208 +0xccc
```

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by awels** [comment]
Fixed by PR #688
