### ISSUE TITLE
CDI operator should cleanup apiservices

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/containerized-data-importer#885]
**BUG REPORT**:
/kind bug

**What happened**:
CDI operator is not cleaning up endpoints when it's deleted.

I created CDI in kubevirt-hyperconverged, then removed it.  Created CDI in openshift-cnv and the api-server fails.   Looks like an endpoint is left around in the kubevirt-hyperconverged ns.

```
[rhallisey@localhost hyperconverged-cluster-operator]$ oc logs cdi-apiserver-799b86cd47-f7t2j -n openshift-cnv
I0716 10:36:54.281929       1 apiserver.go:56] Note: increase the -v level in the api deployment for more detailed logging, eg. -v=2 or -v=3
W0716 10:36:54.282312       1 client_config.go:548] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0716 10:36:54.555020       1 keystore.go:122] Retrieved server key/cert cdi-api.openshift-cnv from kubernetes
F0716 10:36:54.576410       1 apiserver.go:83] Upload api failed to initialize: failed to create webhook: ValidatingAdmissionWebhook [cdi-api-validator] is already registered using services endpoints in a different namespace. Existing we
bhook registration must be deleted before cdi-api can proceed
goroutine 1 [running]:
kubevirt.io/containerized-data-importer/vendor/k8s.io/klog.stacks(0xc0002f7f00, 0xc000376000, 0x12b, 0x2b8)
        /go/src/kubevirt.io/containerized-data-importer/vendor/k8s.io/klog/klog.go:828 +0xd4
kubevirt.io/containerized-data-importer/vendor/k8s.io/klog.(*loggingT).output(0x1dcca00, 0xc000000003, 0xc0000d82c0, 0x1d2e9ae, 0xc, 0x53, 0x0)
        /go/src/kubevirt.io/containerized-data-importer/vendor/k8s.io/klog/klog.go:779 +0x306
kubevirt.io/containerized-data-importer/vendor/k8s.io/klog.(*loggingT).printf(0x1dcca00, 0xc000000003, 0x1213c00, 0x24, 0xc000705f58, 0x1, 0x1)
        /go/src/kubevirt.io/containerized-data-importer/vendor/k8s.io/klog/klog.go:678 +0x14b
kubevirt.io/containerized-data-importer/vendor/k8s.io/klog.Fatalf(0x1213c00, 0x24, 0xc000705f58, 0x1, 0x1)
        /go/src/kubevirt.io/containerized-data-importer/vendor/k8s.io/klog/klog.go:1209 +0x67
main.main()
        /go/src/kubevirt.io/containerized-data-importer/cmd/cdi-apiserver/apiserver.go:83 +0x2be
```

**Comment by rthallisey** [comment]
cc @annastopel @igoihman

**Comment by mhenriks** [comment]
This is already fixed.

Here:  https://github.com/kubevirt/containerized-data-importer/blob/master/pkg/apiserver/apiserver.go#L550

And here:  https://github.com/kubevirt/containerized-data-importer/blob/master/pkg/apiserver/apiserver.go#L622

**Comment by rthallisey** [comment]
Ack.  HCO needs to bump CDI to 1.9.4.

**Comment by rthallisey** [comment]
thanks Michael
